### ISSUE TITLE
Grupos globais com canais em português

### ISSUE THREAD

**Issue by renatosuero** [joselitojunior1/slack-list-brazil#67]
Amigos,  participo de dois grupos que são ativos e bem legais mas são canais.Estou deixando os links para analisarem, de repente vale a penar adicionar.

[Elixir]
Invite https://elixir-slackin.herokuapp.com/ 
Link https://elixir-lang.slack.com
[GO]
Invite https://gophersinvite.herokuapp.com/ 
Link https://gophers.slack.com/

**Comment by joselitojunior1** [comment]
acho válido @renatosuero. só deixa claro qual o grupo que o cara tem que entrar, como o Startup Study Group listado faz.

no aguardo do PR 🚁

**Comment by renatosuero** [comment]
Poxa, que distração, não vi que tinha um canal assim já :/ já fiz a PR
